# Generated by Django 5.0.4 on 2024-05-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invited_talks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=100)),
                ('type_of_event', models.CharField(max_length=100)),
                ('name_of_event', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('topic_of_talk', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=100)),
            ],
        ),
    ]
