# Generated by Django 5.0.4 on 2024-05-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FA', '0002_invited_talks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invited_talks',
            name='name_of_event',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sdp_attended',
            name='name_of_event',
            field=models.CharField(max_length=500),
        ),
    ]
